# Generated by Django 2.0.8 on 2018-09-20 19:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('datesInNeighborhoodFrom', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('datesInNeighborhoodUntil', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('birthYear', models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2018)])),
                ('placeOfBirth', models.CharField(max_length=100)),
                ('occupations', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('blobContent', models.BinaryField(blank=True, max_length=209715200, null=True)),
                ('url', models.URLField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('submissionId', models.AutoField(primary_key=True, serialize=False)),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('mimeType', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('mediaType', models.CharField(choices=[('image', 'Image'), ('audio', 'Audio'), ('video', 'Video'), ('soundcloud', 'SoundCloud'), ('youtube', 'YouTube')], max_length=10)),
                ('mediaHash', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
