# Generated by Django 2.0.8 on 2018-09-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('blobContent', models.BinaryField(null=True)),
                ('url', models.URLField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('submissionId', models.AutoField(primary_key=True, serialize=False)),
                ('submissionDate', models.DateField(auto_now_add=True)),
                ('mediaType', models.CharField(choices=[('Image', 'image'), ('Audio', 'audio'), ('Video', 'video'), ('SoundCloud', 'soundcloud'), ('YouTube', 'youtube')], max_length=10)),
                ('embed', models.TextField(null=True)),
                ('published', models.BooleanField(default=False)),
            ],
        ),
    ]
