# Generated by Django 2.0.8 on 2018-09-25 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='consented',
            field=models.BooleanField(default=False),
        ),
    ]
