# Generated by Django 2.0.8 on 2018-09-10 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180907_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='mimeType',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
