# Generated by Django 2.0.8 on 2018-09-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_submission_consented'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='datesInNeighborhoodFrom',
            new_name='yearsInNeighborhoodFrom',
        ),
        migrations.RenameField(
            model_name='submission',
            old_name='datesInNeighborhoodUntil',
            new_name='yearsInNeighborhoodUntil',
        ),
    ]
