# Generated by Django 2.0.8 on 2018-09-10 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_submission_mimetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='embed',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
