# Generated by Django 2.0.8 on 2018-09-25 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180925_1249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='yearsInNeighborhoodUntil',
            new_name='yearsInNeighborhoodTo',
        ),
    ]
