# Generated by Django 2.0.8 on 2018-09-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180910_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='blobContent',
            field=models.BinaryField(blank=True, max_length=209715200, null=True),
        ),
    ]
