# Generated by Django 2.0.8 on 2018-09-11 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180910_1752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='embed',
        ),
        migrations.AddField(
            model_name='submission',
            name='mediaHash',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
